// Pre-seeded demo data so the feed isn't empty on first load.

export const demoReports = [
  {
    id: "RPT-2031",
    title: "Public school in Anantapur lacks drinking water for 3 weeks",
    summary: "Government primary school with 240 students has had no functional water connection since the borewell pump failed. Multiple complaints unanswered.",
    category: "Education",
    location: "Anantapur, Andhra Pradesh",
    credibility: 89,
    status: "Forwarded to Department",
    department: "Department of School Education",
    supporters: 1284,
    comments: 47,
    submittedAgo: "2 days ago",
    anonymous: true,
    timeline: [
      { stage: "Submitted", at: "2 days ago", note: "Citizen reported with 4 photos" },
      { stage: "AI Triage", at: "2 days ago", note: "Credibility 89/100. Routed to Education." },
      { stage: "Forwarded to Department", at: "1 day ago", note: "Acknowledged by district officer" },
    ],
  },
  {
    id: "RPT-2034",
    title: "Garbage contractor billing for collections never made — Ward 14",
    summary: "Bills filed with the municipality show daily pickup, but residents have CCTV footage showing trucks did not arrive on 11 of 30 days last month.",
    category: "Municipal Corruption",
    location: "Kurnool, Andhra Pradesh",
    credibility: 76,
    status: "Under Review",
    department: "Municipal Corporation",
    supporters: 612,
    comments: 28,
    submittedAgo: "5 hours ago",
    anonymous: true,
    timeline: [
      { stage: "Submitted", at: "5 hours ago", note: "Citizen submitted with CCTV evidence" },
      { stage: "AI Triage", at: "5 hours ago", note: "Credibility 76/100. Specific dates and verifiable claims." },
      { stage: "Under Review", at: "3 hours ago", note: "Awaiting moderator confirmation before public posting" },
    ],
  },
  {
    id: "RPT-2028",
    title: "Streetlights non-functional on highway stretch — accident risk",
    summary: "12 km stretch of NH-44 between Adoni and Yemmiganur has had broken streetlights for over 6 months. Three accidents reported in this period.",
    category: "Public Safety",
    location: "Kurnool District",
    credibility: 94,
    status: "Action Taken",
    department: "National Highways Authority",
    supporters: 3081,
    comments: 119,
    submittedAgo: "3 weeks ago",
    anonymous: false,
    timeline: [
      { stage: "Submitted", at: "3 weeks ago", note: "Reported with GPS-tagged photos" },
      { stage: "AI Triage", at: "3 weeks ago", note: "Credibility 94/100. Cross-referenced accident records." },
      { stage: "Forwarded to Department", at: "3 weeks ago", note: "NHAI acknowledged" },
      { stage: "Action Taken", at: "4 days ago", note: "Repair work begun, 6 lights restored" },
    ],
  },
  {
    id: "RPT-2042",
    title: "Demand for hostel facility for girls in degree college",
    summary: "Government degree college has no hostel. Female students from villages travel 40+ km daily, many drop out by 2nd year. Petition with 800 signatures.",
    category: "Education",
    location: "Nandyal, Andhra Pradesh",
    credibility: 82,
    status: "Under Review",
    department: "Department of Higher Education",
    supporters: 943,
    comments: 64,
    submittedAgo: "1 day ago",
    anonymous: false,
    timeline: [
      { stage: "Submitted", at: "1 day ago", note: "Submitted with petition document" },
      { stage: "AI Triage", at: "1 day ago", note: "Credibility 82/100. Documentation strong." },
      { stage: "Under Review", at: "20 hours ago", note: "Moderator reviewing scope" },
    ],
  },
];

export const demoSchemes = [
  {
    id: "PMK-2024",
    title: "Pradhan Mantri Kaushal Vikas Yojana 4.0",
    type: "Skill Development",
    audience: ["student", "youth", "unemployed"],
    summary: "Free skill certification across 200+ trades. Stipend of ₹8,000/month during training. Applications open quarterly.",
    deadline: "Rolling — next intake July 15",
    source: "Ministry of Skill Development & Entrepreneurship",
  },
  {
    id: "AP-WS-2025",
    title: "AP Women Entrepreneur Loan Scheme",
    type: "Financial Aid",
    audience: ["women", "small-business"],
    summary: "Collateral-free loans up to ₹5 lakh at 4% interest for women starting small businesses in Andhra Pradesh.",
    deadline: "Open until March 31",
    source: "AP State Finance Corporation",
  },
  {
    id: "NSP-MERIT-2025",
    title: "National Means-cum-Merit Scholarship",
    type: "Scholarship",
    audience: ["student"],
    summary: "₹12,000/year for students from families with annual income below ₹3.5 lakh. Class 9 to 12.",
    deadline: "October 31, 2025",
    source: "Ministry of Education",
  },
  {
    id: "PM-KISAN",
    title: "PM Kisan Samman Nidhi",
    type: "Direct Benefit",
    audience: ["farmer"],
    summary: "₹6,000 per year transferred directly to small and marginal farmers in three installments.",
    deadline: "Continuous enrollment",
    source: "Ministry of Agriculture",
  },
  {
    id: "DDR-2024",
    title: "Digital India Rural Connectivity Bill",
    type: "Bill / Legislation",
    audience: ["farmer", "small-business", "women", "youth"],
    summary: "Proposes mandatory broadband to every Gram Panchayat by 2027. Currently in Lok Sabha. Public comment period open.",
    deadline: "Comments due May 30",
    source: "Ministry of Communications",
  },
  {
    id: "SR-PEN-2025",
    title: "Indira Gandhi National Old Age Pension",
    type: "Pension",
    audience: ["senior"],
    summary: "Monthly pension for citizens above 60 from BPL households. Apply through panchayat or municipal office.",
    deadline: "Continuous enrollment",
    source: "Ministry of Rural Development",
  },
  {
    id: "STR-LAW-2025",
    title: "Right to Repair Framework — Public Consultation",
    type: "Bill / Legislation",
    audience: ["youth", "small-business"],
    summary: "Draft framework forcing manufacturers to provide repair manuals & spare parts. Public input requested.",
    deadline: "Comments due June 12",
    source: "Department of Consumer Affairs",
  },
];

export const interestTags = [
  { id: "student", label: "Student" },
  { id: "farmer", label: "Farmer" },
  { id: "women", label: "Women" },
  { id: "small-business", label: "Small Business" },
  { id: "senior", label: "Senior Citizen" },
  { id: "youth", label: "Youth" },
  { id: "unemployed", label: "Job-seeking" },
];

export const statusColors = {
  "Submitted": "bg-line text-ink",
  "Under Review": "bg-saffron/15 text-saffron",
  "Forwarded to Department": "bg-forest/10 text-forest",
  "Action Taken": "bg-forest text-cream",
  "Closed": "bg-muted/20 text-muted",
};
